### ISSUE TITLE
Error "python scripts failed"

### ISSUE THREAD

**Issue by OnePerson10** [friendly-telegram/friendly-telegram.github.io#6]
When I put my number in the script, the scripts stop and says: error python scripts failed

![5D85F775-4EE8-4AE5-8CC2-04D16A3A03FF](https://user-images.githubusercontent.com/39443401/75969078-ac95e500-5ece-11ea-8c1e-bcabe92dd6af.jpeg)

**Comment by AvinashReddy3108** [comment]
Make sure you fed the right API and HASH values into the setup and try again.

**Comment by penn5** [comment]
Not relevant to this repo.
